#!/bin/bash
### BEGIN INIT INFO
# Provides: pi-lightcontrol
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Kurze Beschreibung
# Description: Lange Beschreibung
### END INIT INFO

case $1 in
    start)
        /bin/bash /usr/local/bin/pi-lightcontrol-start.sh
    ;;
    stop)
        /bin/bash /usr/local/bin/pi-lightcontrol-stop.sh
    ;;
    restart)
        /bin/bash /usr/local/bin/pi-lightcontrol-stop.sh
        /bin/bash /usr/local/bin/pi-lightcontrol-start.sh
    ;;
esac
exit 0